project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"

website:
  title: "Minidiss 26/27"
  description: "Project website for mini-dissertation 2026/27 with Dr. Elizabeth Pankratz"
  page-navigation: true
  sidebar:
    style: "docked"
    pinned: true
    search: true
    background: '#DFE7C3'
    contents:
      - href: index.qmd
        text: "Home"
      - section: "Course information"
        contents:
          - href: TODO
            text: "Learn page"
            target: "_blank"
          - href: TODO
            text: "Student handbook"
            target: "_blank"
          - info/sched.qmd
          - info/contact.qmd
          - info/faqs.qmd
          
      - section: "Meeting materials"
        contents:
          - meetings/1.qmd
          # - meetings/2.qmd
          # - href: meetings/3.qmd
          #   text: '3: Coherence in academic writing'
          # - href: meetings/4.qmd
          #   text: '4: Our experiment design'
          # - href: meetings/5.qmd
          #   text: '5: Applying for ethical approval'
          # - href: meetings/6.qmd
          #   text: '6: Live R practice analysis'
          # - href: meetings/7.qmd
          #   text: '7: TBD'
          # - href: meetings/8.qmd
          #   text: '8: Structuring and writing a research paper'
            
      - section: "Additional resources"
        contents:
          - href: https://dl.acm.org/doi/10.1145/1273445.1273458
            text: "Keshav (2006): How to read a paper"
            target: "_blank"
          # - href: https://elizabethpankratz.github.io/posts/01-phd-litreview/
          #   text: "Synthesis matrix input with Google/MS Forms"
          #   target: "_blank"
          # - href: https://uoepsy.github.io/dapr3/2627/flashcards/block1/reporting.html
          #   text: "How to report results"
          #   target: "_blank"
            
format:
  html:
    theme: [flatly, theme.scss]
    css: styles.css
    toc: true

callout-icon: false
